### ISSUE TITLE
Liveness check

### ISSUE THREAD

**Issue by elisabet123** [skoczen/will#357]
We are running our bot in kubernetes, with a docker container. 
Is there a way to know that will is alive and responding on all backends? Either through a command inside docker or through http/tcp.
Otherwise I think that would be a nice addition!

**Comment by skoczen** [comment]
Hey @elisabet123 , sure thing!  Will has a couple of endpoints in out of the box - either should tell you if he's up and running:

1. `/keep-alive/` Just a keep-alive endpoint that he pings to keep himself from sleeping, responds with "I'm Alive!"
2. `/ping` - a ping endpoint, responds with "Pong"
3. `/` - just his standard html home page.  Just shows Will's friendly face, and says hi.

If those work for you, great, feel free to close up - and if you need anything else, just ask!

**Comment by Ashex** [comment]
You probably want to implement another endpoint and do a pythonic check to see if will can do something like [pull a list of channels](https://slackapi.github.io/python-slackclient/basic_usage.html#getting-a-channel-s-info).

**Comment by tvishwanath-arkin** [comment]
Hi @elisabet123 
Would you mind adding the basic kubernetes yml definition here that you used?

**Comment by elisabet123** [comment]
I made a brute force solution with a bash script called restart.sh. This means that every 2 hours our bot is restarted to force reconnection before it is lost. The list of channels might be a more elegant solution :)
```
pkill -f "python2 ./run_will.py"

./run_will.py &
```

@tvishwanath-arkin 
Our will bot is named hedwig, here is the yml we use (somewhat stripped)

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hedwig
  namespace:<namespace>
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hedwig
  template:
    metadata:
      labels:
        app: hedwig
    spec:
      containers:
      - name: redis
        image: redis
      - name: hedwig
        image: <account id>.dkr.ecr.eu-west-1.amazonaws.com/hedwig:<docker tag>
        env:
        - name: WILL_REDIS_URL
          value: localhost:6379
        - name: WILL_SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hedwig-credentials
              key: slack
        - name: WILL_LOGLEVEL
          value: INFO
        - name: WILL_HTTPSERVER_PORT
          value: "9000"
        livenessProbe:
          exec:
            command:
            - /usr/src/app/restart.sh
          initialDelaySeconds: 3
          periodSeconds: 7200

```
